metadata:
  namespace: cms
spec:
  replicas: 1
  template:
    spec:
      image: ghcr.io/clcl0n/cms-site-service:latest

configuration:
  connectionStrings:
    mongoDb: mongodb://mongo:27017
  messagingBroker:
    rabbitMq:
      hostName: localhost
      port: 5672
      userName: rabbitmq
      password: rabbitmq
      virtualHost: /
      ssl:
        enabled: false